// Generated by https://quicktype.io

import 'package:json_annotation/json_annotation.dart';
import 'package:valua_examinee/models/account_alternative.dart';

@JsonSerializable()
class Attendance {
  CurrentAttendance currentAttendance;

  Attendance({
    required this.currentAttendance,
  });
}

@JsonSerializable()
class CurrentAttendance {
  String attendanceId;
  AccountAlternative examinee;
  int position;
  ExamRoom examRoom;
  List<dynamic> attempts;
  DateTime? startTime;
  DateTime? finishTime;
  DateTime createdDate;
  DateTime lastModified;

  CurrentAttendance({
    required this.attendanceId,
    required this.examinee,
    required this.position,
    required this.examRoom,
    required this.attempts,
    this.startTime,
    this.finishTime,
    required this.createdDate,
    required this.lastModified,
  });
}

class ExamRoom {
  String examRoomId;
  String examRoomName;

  ExamRoom({
    required this.examRoomId,
    required this.examRoomName,
  });
}
